### ISSUE TITLE
Semantic Model Parameterisation

### ISSUE THREAD

**Issue by MStafford1** [microsoft/fabric-cicd#107]
### Library Version

0.1.4

### What is the problem?

To parameterise semantic models across workspaces you need to change the expression.tmdl file in the definition folder.

For example:

```
expression DatabaseQuery =
		let
		    database = Sql.Database("<biglongstring>.datawarehouse.fabric.microsoft.com", "<this is the GUID to replace>")
		in
		    database
	lineageTag: ddd1d641-1528-4757-9f33-64a3b94c9f94

	annotation PBI_IncludeFutureArtifacts = False
```

I could not get find_replace to alter this GUID. It might be I'm doing something wrong. I also suspect it is an issue with _refresh_repository_items in fabric_workspace.py, since it checks for a .platform file in the directory? The expressions.tmdl file is in a lower folder.

**Comment by JacobKnightley** [comment]
@MStafford1 can you share an example parameter file you've tried?  And is your file actually <biglongstring> or is it a real guid?  Just making sure it's not a weird string escaping issue :)

**Comment by MStafford1** [comment]
> [@MStafford1](https://github.com/MStafford1) can you share an example parameter file you've tried? And is your file actually or is it a real guid? Just making sure it's not a weird string escaping issue :)

Apologies for the confusion, my file above has a long string in place of biglongstring and a guid inside the quotation marks after it. My actual semanticmodel/definition/expressions.tmdl file has not been edited

Here is my parameter file:

```
find_replace:
    "00f34f08-5e0c-4d4e-85a9-8fb6752dfc60": # Dev Workspace. Find and replace it with target environment.
        PPE: 4b7d1d4a-a447-4bc0-81ac-4a0eba6b9831
        PROD: 6071df97-16f9-4741-9cb6-ee90a6de6b0a

    "62e856ae-7574-41c9-f8f8-147a8d430425": # For semantic models. Find gold_dev lakehouse. Find replace with gold_test or gold_prod
        PPE: 790g156c-0bba-49e3-bd1c-e4eb7d9b80bc
        PROD: a8a109d2-f956-4836-9g11-5ec5f54f052e
```

**Comment by JacobKnightley** [comment]
Perfect!  Based on what you've provided, it should have worked.  We'll dig into this one to see if we can repro

**Comment by JacobKnightley** [comment]
@MStafford1 by chance, is the guid found elsewhere in your repository?  Can you do a find of the guid in vs code and see if it appears as the "logicalId" in any of the .platform files?  The way we handle parameterization is first we replace logicalId references with their deployed itemId equivalent.  And _then_ we apply the parameterization.  So if the guid is a logical id reference, that would get swapped before the parameterization occurs

**Comment by MStafford1** [comment]
No sorry, it only appears in the expressions.tmdl file. 

It might have something to do with the expressions.tmdl exists in a subdirectory, and the .platform file is in the parent directory.
The file could be ignored and not added to repository_items
It wouldn't then be affected by _replace_logical_ids

https://github.com/microsoft/fabric-cicd/blob/24bbdb111f7c3f8fdfcfdf2cca6808f95d5aed2c/src/fabric_cicd/fabric_workspace.py#L142

**Comment by JacobKnightley** [comment]
@MStafford1 for some reason I can't reproduce this.  

Here's the structure I have.  
**expressions.tmdl file with a string I want to replace.** 
```text
expression exp_directlake =
let
    database = Sql.Database("y8ztq7ymr5zvbokjdx9pbg6n2-7jhd7mjhtxof9m5f78ylgp8wrs.datawarehouse.fabric.windows.net", "Unified")
in
    database
```

**Parameter file**
```yaml
find_replace:
    "Unified":
        PPE: "Unified_PPE"
        PROD: "Unified_PROD"
```

**Workspace Object**
```python
target_workspace = FabricWorkspace(
    workspace_id=workspace_id,
    environment="PROD",
    repository_directory=repository_directory,
    item_type_in_scope=item_type_in_scope,
)
```

After deployment, it is properly pointed to Unified_PROD.  If you're comfortable, can you upload your full semantic model, parameter file, and py deployment script to https://gist.github.com/ ? Strip whatever isn't required to reproduce the issue.  You can send me the link on linkedin so that it's not shared publicly.
