### ISSUE TITLE
Need more examples for Find_replace docs page

### ISSUE THREAD

**Issue by MikeCarlo** [microsoft/fabric-cicd#110]
### What is the feature?

Looking at this page:
https://microsoft.github.io/fabric-cicd/latest/how_to/parameterization/#find_replace

Find_replace, feature. it is difficult to understand the pattern you are trying to show. an example or two YAML files will really help understandability with how this works. I don't understand how this will replace a Key that is buried deeper into the item Json.

**Comment by JacobKnightley** [comment]
Thanks!  Can you clarify specifically what is confusing?  If the value you provide is present in any file in the items to be deployed, it will be replaced. Think of it as a brute force replacement.  So regardless of the file, in the root or nested, if it contains the find item, it will be replaced.  We plan to integrate deeper for node specific replacements (i.e. replace specifically the value of the key connectionId in a semantic model), but are deferring until the community requests it.

**Comment by JacobKnightley** [comment]
Note there also is an example yml file.  Maybe this is difficult to find.  

https://microsoft.github.io/fabric-cicd/latest/how_to/example/#parameteryml-file

**Comment by kristofferabs** [comment]
It would be nice to actually see where the find replace will occur. What code is actually being affected by this. I was looking for the key in the code above, and when I don't see it, I do not know how this is used. 

This will be alot more clear if you add an example of the code of the notebook / report or whatever this affects. 

![Image](https://github.com/user-attachments/assets/c3069aa7-85c9-4331-97b0-ebd833baca01)

**Comment by JacobKnightley** [comment]
What we want to be careful about is being clear that this function will find/replace any instance in any file.  So our concern was giving an example of one file may imply it only replaces there.  For instance say you decide to do something silly and define "MAGIC" as your find value and "FOO".  Even if you have one ideal place in a report, this would break every single notebook.  I think it will be more clear once we have more functionality like being able to specify item types or specific file paths you want it to apply to.

**Comment by JacobKnightley** [comment]
@shirasassoon opportunity here for better docs, but also a good indication we need more finite parameters

**Comment by JacobKnightley** [comment]
@shirasassoon sorry one more :). We could also consider adding a feature flag which enables writing to the terminal which files were modified by the find replace.  I.e.  Value X replaced with Y in file Z

**Comment by ghost** [comment]
Hi Team,

This is great library and appricite it publishing. 

, I reviewed Parametrization section and sample give, however ,just wanted to confirm:

<find-this-value> refers to the Dev connection GUID, correct?
<replace-with-this-value> refers to the PROD or PPE connection GUID?
If there are multiple connections, do we repeat the above entry for each connection?


For the spark_pool section:
<instance-pool-id>, type, and name—are these the target environment's pool details?

**Comment by JacobKnightley** [comment]
@MikeCarlo please take a look at the referenced commit to see if this helps resolve your concern about documentation.  Note that we also identified an inherit flaw in our parameterization approach which led to the confusion.  We'll be refactoring this in an upcoming release.  Supporting something like the below.  We'll be getting feedback from the community prior to implementation.  

```yaml
# find_replace will find any matching find_value string in any file under the specified `repository_directory` Workspace object parameter 
# and replace it with the replace_value for the specified `environment` Workspace object parameter 
find_replace:
    # Required Fields
    - find_value: # String to find in the local repository
      replace_value:
        <Environment_1>: # String to replace when deploying to Environment_1
        <Environment_...>: # String to replace when deploying to Environment_...
      # Optional Fields
      item_type: # Replacement occurs only for items of this item type
      item_name: # Replacement occurs only for items of this item name
      file_path: # Replacement occurs only for items with this file path (relative to workspace root)

# spark_pool will find any custom pool references in sparkcompute.yml files and replace
# and replace the id with the provided type and name for the specified `environment` Workspace object parameter
# If this is not specified for environments attached to custom pools, they will be deployed attached to the starter pool
spark_pool:
   # Required Fields
   - insance_pool_id: # String of the insance_pool_id found in the sparkcompute.yml for environment item
     replace_value:
        <Environment_1>:
          type: # "Workspace" or "Capacity" custom pool type when deploying to Environment_1
          name: # Name of custom pool type when deploying to Environment_1
        <Environment_...>:
          type: # "Workspace" or "Capacity" custom pool type when deploying to Environment_...
          name: # Name of custom pool type when deploying to Environment_...
     # Optional Fields
     item_name: # Replacement occurs only for items of this item name

```
