### ISSUE TITLE
Support deployment/configuration of Workspaces

### ISSUE THREAD

**Issue by BradBender** [microsoft/fabric-cicd#137]
### What is the feature?

It would be useful to provision workspaces in code, and define the configuration as part of a complete CI/CD.  The goal being to completely define the environment in code and manage all changes though CI/CD.

As an example, in the reference workspace [https://github.com/microsoft/fabric-cicd/tree/main/sample/workspace](tree/main/sample/workspace)

Folder structure:
```
/workspace
    /<item-name>.<item-type>
        ...
    /<item-name>.<item-type>
    /parameter.yml
    /workspace_config.yml    <=== new
```

If I could include a **workspace_config.yml** file that let me specify various properties for my workspace:
```
 workspace_config:
     uuid: "1b256e9a-xxxx-4fc2-bda4-b583a4234586"
     name: "MyExample Workspace"
     description: "This is my example workspace for ${environment}."
     domain: "Finance"
     contacts: "joe_admin@mycompany.com"
     license_configuration:
         type: "Fabric capacity"
         capacityName: "myF64-SKU"
         semantic_model_storage_format: "small"
     access_permissions:
          - UserPrincipalName: "joe_admin@mycompany.com"
             Permissions: "Admin"
          - UserPrincipalName: "james_likes2watch@mycompany.com"
             Permissions: "Viewer"
```
