### ISSUE TITLE
Support Environment Variables in Parameter.yml

### ISSUE THREAD

**Issue by richbenmintz** [microsoft/fabric-cicd#160]
### What is the feature?

Please allow Azure DevOps Pipeline and Release Variables to be used in the find_replace feature as key value pair:
replace with the value of the key defined in the yaml. 
sorta like (sorry yaml not formatted 100%):

`find_replace:`
`     # SQL Connection Guid`
`     "db52be81-c2b2-4261-84fa-840c67f4bbd0":`
`        PPE: var_1`
`        PROD: var_2`

**Comment by JacobKnightley** [comment]
If there is a session environment variable of ENV:SQLServerConnection, then replace that reference in the yml file when processing.  If we did take this on, it would need to be behind a feature flag so that default behavior is off.  It would be fairly straight forward to implement, list all environment variables.  If there's any matches in the yml file, blindly replace.

```
find_replace:
    - find_value: "db52be81-c2b2-4261-84fa-840c67f4bbd0"
      replace_value:
        PPE: ENV:SQLServerConnection
        PROD: ENV:SQLServerConnection
```
