### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dildick** [microsoft/fabric-cicd#245]
### What is the feature?

I would like to run fabric-cicd from within an azure devops pipeline using an azure subscription and a tenant ID to obtain the token. My client prefers not to use secrets. 
```
az account get-access-token --resource https://api.fabric.microsoft.com --tenant $TID
```
Basically, I want to export this token (Id and expiration date) to my fabric-cicd script where a fabric endpoint object and be instantiated from these variables directly (rather than calling DefaultAzureCredentials())

**Comment by dildick** [comment]
Hello @JacobKnightley, do you have an idea what might be going wrong using fabric-cicd in azure devops?

**Comment by JacobKnightley** [comment]
Hi there!  Have you tried using azurecli instead?  all you need to do is use az cli task which will pick up the service connection auth. 

py file
```python
"""Deploy workspace to Fabric"""

import os
import sys
from pathlib import Path

from azure.identity import AzureCliCredential
from fabric_cicd import FabricWorkspace, change_log_level, publish_all_items, unpublish_all_orphan_items

branch = os.getenv("BUILD_SOURCEBRANCHNAME")

if branch == "Main":
    workspace_id = ""
    environment = "main"
elif branch == "Test":
    workspace_id = ""
    environment = "test"
else:
    workspace_id = ""
    environment = "dev"


root_directory = Path(__file__).resolve().parent.parent
repository_directory = str(root_directory / "workspace" )

# Force unbuffered output like `python -u`
sys.stdout.reconfigure(line_buffering=True, write_through=True)
sys.stderr.reconfigure(line_buffering=True, write_through=True)

# Enable debugging if defined in Azure DevOps pipeline
if os.getenv("SYSTEM_DEBUG", "false").lower() == "true":
    change_log_level("DEBUG")

# Use Azure CLI credential to authenticate
token_credential = AzureCliCredential()

# Explicitly define which of the item types we want to deploy
item_type_in_scope = ["Lakehouse", "Notebook", "Environment"]

# Initialize the FabricWorkspace object with the required parameters
target_workspace = FabricWorkspace(
    workspace_id=workspace_id,
    environment=environment,
    repository_directory=repository_directory,
    item_type_in_scope=item_type_in_scope,
    token_credential=token_credential,
)

# Publish all items defined in item_type_in_scope
publish_all_items(target_workspace)

# Unpublish all items defined in item_type_in_scope not found in repository
unpublish_all_orphan_items(target_workspace, item_name_exclude_regex=r"^DEBUG.*")
```

yaml pipeline
```yaml
trigger:
  branches:
    include:
      - Develop
      - Main
      - Test
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)
              artifact: build
              publishLocation: pipeline
  - stage: Release
    dependsOn: Build
    jobs:
      - job: Release
        pool:
          vmImage: windows-latest
        steps:
          - checkout: none
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: build
              path: $(Pipeline.Workspace)/build
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
              addToPath: true
          - script: |
              pip install fabric-cicd
            displayName: 'Install fabric-cicd'
          - task: AzureCLI@2
            displayName: "Deploy Fabric Workspace"
            inputs:
              azureSubscription: "HelixData-PROD"
              scriptType: "ps"
              scriptLocation: "inlineScript"
              inlineScript: |
                python -u $(Pipeline.Workspace)/build/.deploy/fabric_workspace.py
```
