### ISSUE TITLE
Allow The Parameterization of Variable Libraries

### ISSUE THREAD

**Issue by richbenmintz** [microsoft/fabric-cicd#276]
### What is the feature?

I would like to not manage variable library alternate sets and only have a single default value. The default value would be modified using the parameters.yml file during deployment, sample format below. In a multi developer environment where you could have multiple variable sets for each environment would contain multiple alternate sets and could potentially introduce multiple merge conflicts. 

### Additional context

Sample yaml for the parameters.yml file, not formatted correctly sorry

`variable_libraries: `
` - PPE:`
    ` - library_name: "dsi-vars"`
        `variables:`
        ` - name: var_test`
           `note: 'note_test'`
           `type: String`
           `value: test_value_again_again`
        ` - name: var_string`
           `note: 'testing_notes'`
           `type: String`
           `value: test_string_var_testing`
       `alternate_sets: `
        `- set_name: "alt_set"`
          `variables:`
            `- name: "var_test"`
              `value: "alternate_value_please_to_work"`

**Comment by JacobKnightley** [comment]
would something like this work?  Using jsonpath syntax to look for a specified key?

```yaml
key_value_replace:
  - find_key: $.variables[?(@.name=="SQL_Server")].value
    replace_value:
      PPE: "contoso-ppe.database.windows.net"
      PROD: "contoso-prod.database.windows.net"
    item_type: "VariableLibrary"
  - find_key: $.variables[?(@.name=="Environment")].value
    replace_value:
      PPE: "PPE"
      PROD: "PROD"
    item_type: "VariableLibrary"

```
