### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by b-joubert** [microsoft/fabric-cicd#300]
### What is the question?

Hi,
Firstly, thanks for the nice work on this ;)
I have pipelines deployments failing with "User does not have access to the connection used in the Pipeline. Please verify the user's permissions."
My pipeline contains:
- connections configured with library variables
- connections to Fabric SQL DB
Could this explain the error ?
I could remove library variables and replace information when deploying with parameter.yml file

PS:
I had to add this in the parameter.yml so it passes structure validation ;)
```
find_replace:
    # Dummy for valid parameter file structure
    - find_value: "xxx"
      replace_value:
        TST: "xxx"
        PROD: "xxx"
      item_type: "Notebook"
      item_name: ["Dummy"]

key_value_replace:
...
```
