### ISSUE TITLE
Problem with setting up the parameter.yml, references not updating

### ISSUE THREAD

**Issue by mkutr** [microsoft/fabric-cicd#311]
I am trying to setup a CICD process using fabric CICD, yet I cannot get the parametrisation working. For the moment I wanted to simply change the reference for one of the lakehouses:

This is the fragment of my notebook, I anonymized the UIDs:
```
# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "11111111-2222-3333-4444-555555555555",
# META       "default_lakehouse_name": "LakehouseBronze",
# META       "default_lakehouse_workspace_id": "66666666-7777-8888-9999-000000000000",
# META       "known_lakehouses": [
# META         {
# META           "id": "11111111-2222-3333-4444-555555555555"
# META         }
# META       ]
# META     }
# META   }
# META }

...
```

This is my parameter.yml:

```
find_replace:
    # Bronze Lakehouse GUID
    - find_value: "11111111-2222-3333-4444-555555555555" 
      replace_value:
          TEST: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      item_type: ["Notebook", "DataPipeline", "Lakehouse"]
```

Yet this doesn't work, I still get the notebook in test linked to the lakehouse from the dev environment. Debugging doesn't give me any errors. In your guide you mention that I shouldn't link the test and prod environments gits, so how should I find the GUID of the items in an another workspaces?
