### ISSUE TITLE
Support an "ALL" / "*" environment in parameter.yml

### ISSUE THREAD

**Issue by RuiRomano** [microsoft/fabric-cicd#320]
### What is the feature?

I want to configure a rule that its the same for all environments. For example set the activePage per report:

```
key_value_replace:    
    - find_key: $..activePageName
      replace_value:
          *: 3cf1cedb01b04a3b132e
      file_path: Report01.Report/definition/pages/pages.json
```
