### ISSUE TITLE
Documentation Feedback - Bug in Release Pipeline Example with Variable Groups

### ISSUE THREAD

**Issue by dimkaart** [microsoft/fabric-cicd#377]
### URL to documentation

https://microsoft.github.io/fabric-cicd/latest/example/release_pipeline/#variable-groups

### Feedback

The current yaml file of an azure devops release pipeline with variable groups fail to executes in the current setup. The reason for that is the `|` character in the last task when you list all the arguments for the python file.

There is a critical semantic difference between using `>-` and | for your arguments block. For this specific use case, `>-` (folded style) is the correct choice, and `|` (literal style) would cause your script execution to fail. I would suggest to replace the `|` character with `>-`. 

**Old Code Example:**
```yaml
trigger:
  branches:
    include:
      - dev
      - main

parameters:
- name: items_in_scope
  displayName: Enter Fabric items to be deployed
  type: string
  default: '["Notebook","DataPipeline","Environment"]'

variables:
- group: Fabric_Deployment_Group_KeyVault # Linked to Azure Key Vault and contains tenant id, SPN client id, and SPN secret
- group: Fabric_Deployment_Group  # Contains workspace_name and repository directory name

stages:
  - stage: Build_Release
    jobs:
      - job: Build
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
              addToPath: true
          - script: |
              pip install fabric-cicd
            displayName: 'Install fabric-cicd'
          - task: PythonScript@0
            inputs:
              scriptSource: 'filePath'
              scriptPath: '.deploy/fabric_workspace.py'
              arguments: |
                --spn_client_id $(client_id) # from Fabric_Deployment_Group_KeyVault
                --spn_client_secret $(client_secret) # from Fabric_Deployment_Group_KeyVault
                --tenant_id $(tenant_id) # from Fabric_Deployment_Group_KeyVault
                --workspace_id $(workspace_id) # from Fabric_Deployment_Group
                --environment $(environment_name) # from Fabric_Deployment_Group
                --repository_directory $repository_directory # from Fabric_Deployment_Group
                --item_types_in_scope ${{ parameters.items_in_scope }}
```

**New Code Example:**
```yaml
trigger:
  branches:
    include:
      - dev
      - main

parameters:
- name: items_in_scope
  displayName: Enter Fabric items to be deployed
  type: string
  default: '["Notebook","DataPipeline","Environment"]'

variables:
- group: Fabric_Deployment_Group_KeyVault # Linked to Azure Key Vault and contains tenant id, SPN client id, and SPN secret
- group: Fabric_Deployment_Group  # Contains workspace_name and repository directory name

stages:
  - stage: Build_Release
    jobs:
      - job: Build
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
              addToPath: true
          - script: |
              pip install fabric-cicd
            displayName: 'Install fabric-cicd'
          - task: PythonScript@0
            inputs:
              scriptSource: 'filePath'
              scriptPath: '.deploy/fabric_workspace.py'
              arguments: >-
                --spn_client_id $(client_id) # from Fabric_Deployment_Group_KeyVault
                --spn_client_secret $(client_secret) # from Fabric_Deployment_Group_KeyVault
                --tenant_id $(tenant_id) # from Fabric_Deployment_Group_KeyVault
                --workspace_id $(workspace_id) # from Fabric_Deployment_Group
                --environment $(environment_name) # from Fabric_Deployment_Group
                --repository_directory $repository_directory # from Fabric_Deployment_Group
                --item_types_in_scope ${{ parameters.items_in_scope }}
```

P.S.: Additionally I would suggest to replace the windows VM image with an ubuntu VM image, but that is not necessary to run successfully the code.
